SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS STAFF;
DROP TABLE IF EXISTS SUBJECT;
DROP TABLE IF EXISTS USER_ROLE;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS USER_ROLE;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS STUDENT_CLASS;
DROP TABLE IF EXISTS DIRECTION;

CREATE TABLE USER_ROLE (
  username        VARCHAR(32),
  role            VARCHAR(32)
);

DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT (
    student_no      VARCHAR(32) PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    telephone       VARCHAR(32),
    gender          VARCHAR(32),
    dob             DATE,
    class_id        INTEGER NOT NULL
);

DROP TABLE IF EXISTS STAFF;
CREATE TABLE STAFF (
   staff_no     VARCHAR(32) PRIMARY KEY,
   name         VARCHAR(255) NOT NULL,
   telephone    VARCHAR(32),
   gender       VARCHAR(32),
   dob          DATE,
   academic_rank       VARCHAR(32)
);

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    username        VARCHAR(32) PRIMARY KEY,
    password        VARCHAR(256),
    email           VARCHAR(32),
    enabled         BOOLEAN
);

DROP TABLE IF EXISTS STUDENT_CLASS;
CREATE TABLE STUDENT_CLASS (
    id              INTEGER PRIMARY KEY AUTO_INCREMENT,
    name            VARCHAR(32) NOT NULL ,
    enroll_year     VARCHAR(32) NOT NULL ,
    subject_id      INTEGER NOT NULL ,
    direction_id    INTEGER
);
ALTER TABLE STUDENT_CLASS  AUTO_INCREMENT=1;

DROP TABLE IF EXISTS DIRECTION;
CREATE TABLE DIRECTION (
    id          INTEGER PRIMARY KEY AUTO_INCREMENT,
    name        VARCHAR(32) NOT NULL,
    subject_id  INTEGER NOT NULL,
    status      VARCHAR(32) NOT NULL
);
ALTER TABLE DIRECTION  AUTO_INCREMENT=1000000;

DROP TABLE IF EXISTS SUBJECT;
CREATE TABLE SUBJECT (
    id          INTEGER PRIMARY KEY AUTO_INCREMENT,
    name        VARCHAR(32) NOT NULL,
    status      VARCHAR(32) NOT NULL,
    director_no VARCHAR(32)
);
ALTER TABLE SUBJECT  AUTO_INCREMENT=1;

ALTER TABLE STUDENT
    ADD FOREIGN KEY (class_id)
        REFERENCES STUDENT_CLASS(id);

ALTER TABLE STUDENT
    ADD FOREIGN KEY (student_no)
        REFERENCES USER(username);

ALTER TABLE STAFF
    ADD FOREIGN KEY (staff_no)
        REFERENCES USER(username);

ALTER TABLE DIRECTION
    ADD FOREIGN KEY (subject_id)
        REFERENCES SUBJECT(id);

ALTER TABLE STUDENT_CLASS
    ADD FOREIGN KEY (subject_id)
        REFERENCES SUBJECT(id);

ALTER TABLE STUDENT_CLASS
    ADD FOREIGN KEY (direction_id)
        REFERENCES DIRECTION(id);

ALTER TABLE SUBJECT
    ADD FOREIGN KEY (director_no)
        REFERENCES STAFF(staff_no);

SET FOREIGN_KEY_CHECKS = 1;